spring.application.name=watchd-v2
spring.datasource.url=jdbc:postgresql://localhost:5432/watchd
spring.datasource.username=barryrichards

tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.read.access.token=${TMDB_READ_ACCESS_TOKEN}